name: DiT
channels:
  - pytorch
  - nvidia
dependencies:
  - pip 
  - python
  - pytorch=1.13
  - torchvision
  - pytorch-cuda=11.7
  - pip:
    - accelerate==0.12.0
    - timm
    - diffusers
    - pycocotools
    - transformers
    - einops
    - pytorch-fid
    - wandb
    - torch-xla