name: DiT
channels:
  - pytorch
  - nvidia
dependencies:
  - pip 
  - python >= 3.8
  - pytorch >= 1.13
  - torchvision
  - pytorch-cuda=11.7
  - pip:
    - timm
    - diffusers
    - accelerate
    - pycocotools